---
- name: set location of org.eclipse.ui.ide.pref
  set_fact:
    eclipse_ui_ide_pref: "{{ eclipse_unpack_dir }}/{{ eclipse_defaults.ui_id_prefs.filename }}"

- name: check if org.eclipse.ui.ide.prefs exists
  stat:
    path: "{{ eclipse_ui_ide_pref }}"
  register: eclipse_ui_ide_pref_stat

- name: Configure settings/org.eclipse.ui.ide.prefs
  lineinfile:
    dest: "{{ eclipse_ui_ide_pref }}"
    state: present
    backup: no
    regexp: "^{{ item.key }}=.*$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ eclipse_defaults.ui_id_prefs.settings }}"
  when: eclipse_ui_ide_pref_stat.stat.exists
  tags: [eclipse_config]
