---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Ensure required apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - apt-transport-https
          - bzip2
          - ca-certificates
          - curl
          - gzip
          - tar
          - unzip
      - name: Ensure additional apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - bmon
          - bridge-utils
          - chromium-browser
          - git
          - glogg
          - imagemagick
          - jmeter
          - libreoffice-calc
          - maven
          - nethogs
          - subversion
    roles:
      - role: infOpen.locales
        become: yes
      - role: ferrarimarco.nano
        become: yes
